### ISSUE TITLE
Hangup when receiver is created

### ISSUE THREAD

**Issue by TheNeikos** [jkristell/infrared#78]
Heya! First of all, thank you a lot for making this crate.

I am currently trying to test it out on my atmega328p (The metro mini from adafruit) and have an issue with the whole thing freezing when I try to build a receiver.

I have the following setup:

```rust
type ReceiverPin = Pin<Input<Floating>, PD7>;

type Proto = Nec<NecCommand>;
type ProtoCmd = <Proto as Protocol>::Cmd;

type ReceiverKind = infrared::Receiver<Proto, Poll, PinInput<ReceiverPin>>;

let receiver: ReceiverKind = Receiver::with_pin(40_000, pins.d7.into_floating_input());
```

And it never progresses past that point. I have a small suspicion that this might be due to 328p's pointer width of 16, and thus having a maximum `usize` of just `2^16-1` which is way smaller than even the 'default' resolution of `1_000_000`.

I am not sure how to verify whether it is panicking/aborting or not, but looking through the code one can find places like this: https://github.com/jkristell/infrared/blob/master/src/protocol/utils.rs#L39 where a default type of 'usize' is inferred but that gets truncated to 0 probably which would then divide by 0.

Throughout the crate `1_000_000` is used, with `usize` as types, a quick and dirty 'search and replace' fixed that issue I had (but I did not get my HX1838 to be detected yet).

**Comment by jkristell** [comment]
Hi and thanks for the detailed bug description. 

AVR my old friendemy :) I actually changed the the "goto integer type" from u32 to usize to give the AVR a chance to work. But I haven't tested the code on my arduino for some time. There are probably some assumptions on the usize >= 32 bits now...

There was a previous bug report #55  that made me to investigate why Infrared didn't work on AVR. In my last reply in that thread I link to some example code that at the time did work for me.

I was hopping that the AVR backend would be fixed so that I could get away with soft u32 arithmetic.
